name = "Gradient"
category = "Basic"
author = "Dex Prime"
version = "0.1"

description = """
A procedural linear gradient demonstrating
coordinate transformations and interpolation.
"""

fragment_shader = "shader.frag"
parameters = "parameters.toml"