name = "Gradient"
category = "Basic"
author = "Dex Prime"
version = "0.1"

description = """
A basic procedural gradient demonstrating
coordinate transforms and color interpolation.
"""

fragment_shader = "shader.frag"
parameters = "parameters.toml"