# ---------- Transform ----------

u_offset = [0.0, 0.0]
u_rotation = 0.0
u_scale = [1.0, 1.0]

# ---------- Gradient ----------

u_start = -0.5
u_end = 0.5

u_repeat = 1.0
u_repeat_enabled = false

u_invert = false

# ---------- Curve ----------

u_exponent = 1.0

# ---------- Palette ----------

u_palette_size = 2

u_palette_0 = [0.0, 0.0, 0.0]
u_palette_1 = [1.0, 1.0, 1.0]
u_palette_2 = [1.0, 0.0, 0.0]
u_palette_3 = [1.0, 1.0, 0.0]

# ---------- Appearance ----------

u_intensity = 1.0