# ---------- Transform ----------

u_offset = [0.0, 0.0]
u_rotation = 0.0
u_scale = [1.0, 1.0]

# ---------- Geometry ----------

u_radius_frequency = 20.0
u_arm_count = 5

# ---------- Animation ----------

u_rotation_speed = 1.0

# ---------- Fill ----------

u_fill_mode = 1

u_arm_width = 0.5

u_edge_softness = 0.5
u_leading_edge_softness = 0.5
u_trailing_edge_softness = 0.5

# ---------- Palette ----------

u_palette_size = 6

u_palette = [
    [0.89, 0.01, 0.01],
    [1.00, 0.55, 0.00],
    [1.00, 0.93, 0.00],
    [0.00, 0.50, 0.15],
    [0.00, 0.30, 1.00],
    [0.46, 0.03, 0.53]
]

u_palette_mode = 1

# ---------- Appearance ----------

u_intensity = 1.0