# ---------- Transform ----------

u_offset = [0.0, 0.0]
u_rotation = 0.0
u_scale = [1.0, 1.0]


# ---------- Spiral ----------

u_radius_frequency = 20.0
u_angle_frequency = 5.0

u_rotation_speed = 1.0


# ---------- Appearance ----------

u_color_1 = [0.0, 0.0, 0.0]
u_color_2 = [1.0, 1.0, 1.0]

u_intensity = 1.0